steps:

-   id: "Rodando Docker Compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f','docker-compose.yaml', 'up', '-d']

#adicione este step depois do up -d

-   id: "Rodando docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: ['ps']

-   id: "Push da imagem gerada"
    name: 'gcr.io/cloud-builders/docker'
    args:
        - 'build'
        - '--build-arg'
        - 'DOCKER_COMPOSE_VERSION=${_DOCKER_COMPOSE_VERSION}'
        - '-t'
        - 'gcr.io/$PROJECT_ID/golangci:latest'
        - '.'
    images:
        - 'gcr.io/$PROJECT_ID/golangci:latest'


