steps:

-   id: "Buildando o soma.go"
    name: 'mirror.gcr.io/library/golang'
    env: ['GO111MODULE=on']
    args: ['go','build','src/main/soma.go']

-   id: "Rodando teste unitario"
    name: 'mirror.gcr.io/library/golang'
    args: ["test","src/main/soma_test.go"]

-   id: "Push da imagem gerada"
    name: 'gcr.io/cloud-builders/docker'
    args:
        - 'build'  
        - '--build-arg'
        - 'version=1.1.0'
        - '-t'
        - 'gcr.io/$PROJECT_ID/golangci:latest'
        - '-t'
        - 'gcr.io/$PROJECT_ID/golangci:1.1.0'
        - '.'
images:
    - 'gcr.io/$PROJECT_ID/golangci:latest'


