steps:

-   id: "Buildando o soma.go"
    name: 'mirror.gcr.io/library/golang'
    args: ['go','build','soma.go']
    env: ['GOPATH=.']

-   id: "Rodando o teste unitario soma_test.go"
    name: 'mirror.gcr.io/library/golang'
    args: ['test','soma_test.go', '-v']
    env: ['GOPATH=.']

-   id: "Rodando o soma.go"
    name: 'mirror.gcr.io/library/golang'
    env: ['GO111MODULE=on', 'GOPATH=.']
    args: ['go','run','soma.go']

-   id: "Push da imagem gerada"
    name: 'gcr.io/cloud-builders/docker'
    args:
        - 'build'  
        - '--build-arg'
        - 'version=1.1.0'
        - '-t'
        - 'gcr.io/$PROJECT_ID/golangci:latest'
        - '-t'
        - 'gcr.io/$PROJECT_ID/golangci:1.1.0'
        - '.'
images:
    - 'gcr.io/$PROJECT_ID/golangci:latest'


