steps:

-   id: "Rodando Docker Compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f','docker-compose.yaml', 'up', '-d']

-   id: "Rodando docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: ['ps']

-   id: "Push da imagem gerada"
    name: 'gcr.io/cloud-builders/docker'
    args:
        - 'build'
        - '-t'
        - 'gcr.io/$PROJECT_ID/golangci:latest'
        - '.'
images:
    - 'gcr.io/$PROJECT_ID/golangci:latest'


