version: '3'

services:
    app:
        build: .
        container_name: golangApp
        ports:
            - "6060:8080"
        depends_on: 
            - redis
    redis:
        image: "redis:alpine"